## Write a Python program to print the NumPy version in your system

In [2]:
import numpy as np
print("NumPy version is %s "%np.version.version)

NumPy version is 1.15.0 


## Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [17]:
ip_1 = input("Enter numeric values, comma separated: ")
ip_2 = ip_1.split(',')
ip_3 = list(map(float, ip_2))
arr = np.zeros((len(ip_3)))
for index, i in enumerate(ip_3):
    arr[index] = i
print(arr)

Enter numeric values, comma separated: 3,4,5,6,7
[3. 4. 5. 6. 7.]


## Create a 3x3 matrix with values ranging from 2 to 10

In [18]:
arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Write a Python program to create a null vector of size 10 and update sixth value to 11

In [61]:
arr = np.empty(10)
arr[5] = 11
np.set_printoptions(suppress=True)
arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

## Write a Python program to create a array with values ranging from 12 to 38

In [24]:
arr = np.arange(12,38).reshape(2,13)
arr

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]])

## Write a Python program to reverse an array (first element becomes last).

In [105]:
import numpy as np
ip_1 = input("Enter numeric values, comma separated: ")
ip_2 = ip_1.split(',')
ip_3 = list(map(float, ip_2))
ip_4 = np.array(ip_3)
arr1_rev = np.empty(ip_4.shape)
for index, i in enumerate(ip_4):
    index+=1
    arr1_rev[-index] = i
arr1_rev

Enter numeric values, comma separated: 9,4,5,6,7


array([7., 6., 5., 4., 9.])

## Write a Python program to an array converted to a float type.

In [138]:
arr2 = np.ones(((3,4)), dtype='int32')
for j in arr2:
    for k in j:
        k = k.astype(float)
        

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)