## Write a Python program to print the NumPy version in your system

In [2]:
import numpy as np
print("NumPy version is %s "%np.version.version)

NumPy version is 1.15.0 


## Write a Python program to convert a list of numeric value into a one-dimensional NumPy array.

In [17]:
ip_1 = input("Enter numeric values, comma separated: ")
ip_2 = ip_1.split(',')
ip_3 = list(map(float, ip_2))
arr = np.zeros((len(ip_3)))
for index, i in enumerate(ip_3):
    arr[index] = i
print(arr)

Enter numeric values, comma separated: 3,4,5,6,7
[3. 4. 5. 6. 7.]


## Create a 3x3 matrix with values ranging from 2 to 10

In [18]:
arr = np.arange(2,11).reshape(3,3)
print(arr)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


## Write a Python program to create a null vector of size 10 and update sixth value to 11

In [61]:
arr = np.empty(10)
arr[5] = 11
np.set_printoptions(suppress=True)
arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

## Write a Python program to create a array with values ranging from 12 to 38

In [24]:
arr = np.arange(12,38).reshape(2,13)
arr

array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37]])

## Write a Python program to reverse an array (first element becomes last).

In [36]:
import numpy as np
ip_1 = input("Enter numeric values, comma separated: ")
ip_2 = ip_1.split(',')
ip_3 = list(map(float, ip_2))
ip_4 = np.array(ip_3)
print('Original array:')
print(ip_4)
print('\n')
arr1_rev = np.empty(ip_4.shape)
for index, i in enumerate(ip_4):
    index+=1
    arr1_rev[-index] = i
print("Reversed array:")
print(arr1_rev)

Enter numeric values, comma separated: 2,3,4,5,6
Original array:
[2. 3. 4. 5. 6.]


Reversed array:
[6. 5. 4. 3. 2.]


## Write a Python program to an array converted to a float type.

In [13]:
arr = np.array([[1.2,2.3,2.4],[4.5,.5,.6]])
print('Array in float values')
print(arr)
print('\n')
print('Array in integer values',)
print(arr.astype(int))

Array in float values
[[1.2 2.3 2.4]
 [4.5 0.5 0.6]]


Array in integer values
[[1 2 2]
 [4 0 0]]


## Write a Python program to create a 2d array with 1 on the border and 0 inside

In [33]:
arr3 = np.zeros((6,6))
print("Original array: ")
print(arr3)
arr3[0] = np.ones(arr3.shape[1])
arr3[-1] = np.ones(arr3.shape[1])
i = 1
while i < (arr3.shape[1]-1):
    arr3[i][0] = 1
    arr3[i][-1] = 1
    i += 1
print('\n')
print("Array after applying boarde: ")
print(arr3)

Original array: 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Array after applying boarde: 
[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


## Write a Python program to add a border (filled with 0's) around an existing array

In [76]:
arr4 = np.arange(1,10).reshape((3,3))
print("Original array: ")
print(arr4, end='\n\n')
arr5 = np.pad(arr4, pad_width=1, mode='constant', constant_values=0)
print("Broadcasting of arra:")
print(arr5)

Original array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Broadcasting of arra:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]


## Write a Python program to create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
p = int(input("Enter the square order of matrix: "))
arr = np.ones((p,p), dtype='int32')

arr[::2,::2] = 0
arr[1::2,1::2] = 0
print("Checkerboard pattern: ")
print(arr)

Enter the square order of matrix: 8
Checkerboard pattern: 
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Write a Python program to convert a list and tuple into arrays.

In [86]:
a = [1,2,3,4]
print("List is ", end="")
print(a)

a = np.asarray(a)
print("List to array is ", end="")
print(a)

b = ((1,2,3,4),(5,6,7,8))
print("Tuple is ", end="")
print(b)
b = np.asarray(b)
print("Tuple to array is ", end="")
print(b)

List is [1, 2, 3, 4]
List to array is [1 2 3 4]
Tuple is ((1, 2, 3, 4), (5, 6, 7, 8))
Tuple to array is [[1 2 3 4]
 [5 6 7 8]]


## Write a Python program to append values to the end of an array.

In [93]:
arr2 = np.arange(9).reshape(3,3)
print("Original array is ", end="")

print(arr2)
np.append(arr2,[[9,10,11]], axis=0)

Original array is [[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

## Write a Python program to create an empty and a full array

In [108]:
arr = np.empty((4,4))
np.set_printoptions(suppress=True)
print("Empty array is ")
print(arr, end='\n\n')
arr2 = np.full((3,3),10)
print("Full array is ")
print(arr2)

Empty array is 
[[ 0.00000000e+000  0.00000000e+000  0.00000000e+000  0.00000000e+000]
 [ 0.00000000e+000  0.00000000e+000  0.00000000e+000  4.44659081e-322]
 [-2.68156159e+154 -2.00390401e+000 -2.68156159e+154 -2.32036231e+077]
 [ 1.97626258e-323  0.00000000e+000  0.00000000e+000  0.00000000e+000]]

Full array is 
[[10 10 10]
 [10 10 10]
 [10 10 10]]


## Write a Python program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array

In [116]:
arr = np.array([[10,11.2,5.6],[5.4,78.6,45.67],[45.6,76.4,-56.7]])
print("Temperatures is degress is: ")
print(arr, end='\n\n')
fahre = arr*(9/5) + 32
print("Equivalent temperatures if Fahrenhite is: ")
print(fahre)

Temperatures is degress is: 
[[ 10.    11.2    5.6 ]
 [  5.4   78.6   45.67]
 [ 45.6   76.4  -56.7 ]]

Equivalent temperatures if Fahrenhite is: 
[[ 50.     52.16   42.08 ]
 [ 41.72  173.48  114.206]
 [114.08  169.52  -70.06 ]]


## Write a Python program to find the real and imaginary parts of an array of complex numbers.

In [130]:
a = np.array([[1+2j, 3+4j, 5+6j],[3.4+4.4j,6.5+5.23j,90.5-3.45j]])
print("Imaginary matrix is:")
print(a, end='\n\n')

print("Real part is")
print(a.real,end='\n\n')

print("Imaginary part is")
print(a.imag,end='\n\n')

Imaginary matrix is:
[[ 1. +2.j    3. +4.j    5. +6.j  ]
 [ 3.4+4.4j   6.5+5.23j 90.5-3.45j]]

Real part is
[[ 1.   3.   5. ]
 [ 3.4  6.5 90.5]]

Imaginary part is
[[ 2.    4.    6.  ]
 [ 4.4   5.23 -3.45]]



## Write a Python program to find common values between two arrays

In [137]:
a = np.array([[9,5,6],[4,2,3],[6,3,4]])
b = np.array([[-2,3,4],[4,3,2],[8,7,5],[9,3,4]])
np.intersect1d(a,b)

array([2, 3, 4, 5, 9])

## Write a Python program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [5]:
a = np.array([[9,5,6],[4,2,3],[6,3,4]])
b = np.array([[-2,3,4],[4,3,2],[8,7,5],[9,3,4]])
np.union1d(a,b)

array([-2,  2,  3,  4,  5,  6,  7,  8,  9])

## Write a Python program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays. 

In [6]:
a = np.array([[9,5,6],[4,2,3],[6,3,4]])
b = np.array([[-2,3,4],[4,3,2],[8,7,5],[9,3,4]])
np.setxor1d(a,b)

array([-2,  6,  7,  8])

## Write a Python program to create an array with 10^3 elements

In [18]:
arr = np.random.randint(0,1000, size=1000)
arr
if 999 in arr:
    print(True)
else:
    print(False)

True
